new: Added my Warp theme: dmilith
warpdotdev/themes pull request #26
Opened 2022-04-20 09:58 UTC by dmilith

# Pull Request Template

## Discord username (optional)
dmilith#1284

If you're in our Discord server please include your formatted like so: elvis#4747.

This is so we can give you the Contributor Discord role.
Note: It must be labelled like so: username#4747 (make sure to include the #XXXX).

## Name of theme
dmilith

Please include the name of the theme.

## How Has This Been Tested?

Have your run the python script?

2022-04-28 18:09 UTC, elviskahoro commented
Hey dmilith,

Thanks for opening this PR and adding a new theme. You're the first PR with a custom background image included. We aren't able to include the image because of licensing and also because we're trying to keep the repo size as small as possible.

Could you remove the background image from the PR but add a comment in the yaml with a link to where people could download it?

Sorry that it took so long to get back to you!

2022-04-28 18:11 UTC, elviskahoro commented on standard/dmilith.yaml
> +background_image:
Could you comment this section out and also include a comment with a link to where someone could download the picture?

Similar to here: https://github.com/warpdotdev/themes/blob/main/warp_bundled/dark_city.yaml#L7

2022-04-28 18:12 UTC, elviskahoro requested changes
Hey dmilith,

Thanks for opening this PR and adding a new theme. You're the first PR with a custom background image included. We aren't able to include the image because of licensing and also because we're trying to keep the repo size as small as possible.

Could you remove the background image from the PR but add a comment in the yaml with a link to where people could download it?

Sorry that it took so long to get back to you!

2022-04-28 18:18 UTC, elviskahoro commented on standard/dmilith.yaml
> +background_image:
To be clear, just the background image section not foreground and background haha.

2022-09-22 15:14 UTC, dannyneira commented
@dmilith Any updates on the background image comment above? We'd really like to merge this and add it to the https://github.com/daltonmenezes/aura-theme repo for others to enjoy.

2022-10-02 11:01 UTC, dmilith commented
@dannyneira  The image was taken from the free image source. If you want to save the colours, just drop the image background. (Support for the transparent terminal in Warp would be better than this)

2022-10-03 17:44 UTC, elviskahoro commented
@dmilith can you remove the standard/dmilith_bg.jpg file and then we'll go ahead and merge it. Thanks again!

2022-10-11 20:11 UTC, closed without merging