Some themes from Cyberpunk 2077 and Cyberpunk: Edgerunners
warpdotdev/themes pull request #49
Opened 2022-10-25 18:08 UTC by rexgraystone

## Discord

Zbhadboi#0565

## Testing

python3 ./scripts/gen_theme_previews.py Cyberpunk/2077/yaml/
Generating for Cyberpunk_2077_-\_Night_City.yaml
Generating for Cyberpunk_2077_-_V.yaml

python3 ./scripts/gen_theme_previews.py Cyberpunk/Edgerunners/yaml/
Generating for Edgerunners_-\_David.yaml
Generating for Edgerunners_-_Lucy_and_David_Jump.yaml

2022-11-07 15:48 UTC, elviskahoro commented
@rexgraystone hey raghav sorry that I'm getting to this late. Had a conference and retreat so i've been busy. We can't accept PR's with images. 
Can you:
- remove the images
- comment out path

The comment you've included in the yaml with a link to where they can download it, is more than enough!

Thanks again!

elvis!

2022-11-07 15:49 UTC, elviskahoro commented on .gitignore
> +warpThemes.code-workspace
Please remove

2022-11-07 15:49 UTC, elviskahoro commented on Cyberpunk/2077/yaml/Cyberpunk_2077_-_Night_City.yaml
> +  path: Cyberpunk/2077/Images/Night_City.jpg
Please comment out.

2022-11-07 15:49 UTC, elviskahoro commented on Cyberpunk/2077/yaml/Cyberpunk_2077_-_V.yaml
> +  path: Cyberpunk/2077/Images/V.jpg
Please comment out

2022-11-07 15:50 UTC, elviskahoro commented on Cyberpunk/Edgerunners/yaml/Edgerunners_-_David.yaml
> +  path: Cyberpunk/Edgerunners/Images/David.jpg
Please comment out!

2022-11-07 15:50 UTC, elviskahoro commented on Cyberpunk/Edgerunners/yaml/Edgerunners_-_Lucy_and_David_Jump.yaml
> +  path: Cyberpunk/Edgerunners/Images/Lucy_and_David_Jump.jpg
please comment out

2022-11-07 15:51 UTC, elviskahoro commented on Cyberpunk/README.md
> +| [Edgerunners - Lucy and David Jump](https://github.com/rexgraystone/warpCyberpunk/blob/Cyberpunk/Cyberpunk/Edgerunners/yaml/Edgerunners_-_Lucy_and_David_Jump.yaml) | ![Edgerunners - Lucy and David
Please remove this as well.

2022-11-07 15:51 UTC, elviskahoro requested changes
Thanks in advance!

2022-11-08 16:10 UTC, elviskahoro commented
@rexgraystone 
We need to comment out: "opacity" as well since this is for when we do have background images.

2022-11-09 02:33 UTC, rexgraystone commented
> @rexgraystone We need to comment out: "opacity" as well since this is for when we do have background images.

I have updated. Please check for the same

2022-11-11 02:06 UTC, elviskahoro commented
Let's ship it!

2022-11-11 02:06 UTC, elviskahoro approved these changes

2022-11-11 02:06 UTC, merged